runtime: aspnetcore
env: flex

# General settings:
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.8

# Environment variables:
env_variables:
  ASPNETCORE_ENVIRONMENT: "Production"

